GFS/Models/Policies/Deceased.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GFS.Models.Policies
{
    public class Deceased
    {
        [Required]
        [Key]
        public int deceasedNo { get; set; }

        [Required]
        [DisplayName("First Name(s):")]
        public string firstName { get; set; }

        [Required]
        [DisplayName("Last Name:")]
        public string lastName { get; set; }

        [NotMapped]
        public string albumArtUrl { get; set; }

        [Required]
        [DisplayName("ID Number:")]
        public string idNo { get; set; }

        [Required]
        [DisplayName("Age:")]
        public int age { get; set; }

        [Required]
        [DisplayName("Place of Death")]
        public string placeofdeath { get; set; }

        [Required]
        [DisplayName("Cause Of Death:")]
        [DataType(DataType.MultilineText)]
        public string causeOfDeath { get; set; }

        [Required]
        [DisplayName("Date Of Death:")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DateOfDeath { get; set; }

        [DisplayName("Policy No:")]
        public string policyNo { get; set; }
        public virtual ICollection<NewMember> NewMembers { get; set; }
       public virtual ICollection<FileDetail> FileDetails { get; set; }
    }
}

GFS/Controllers/Policies/DeceasedsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GFS.Models;
using GFS.Models.Policies;
using System.IO;

namespace GFS.Controllers.Policies
{
    public class DeceasedsController : Controller
    {
        private GFSContext db = new GFSContext();

        // GET: Deceaseds
        public ActionResult Index()
        {
            return View(db.Deceaseds.ToList());
        }
        public ActionResult Create()
        {
            return View();
        }
        //public ActionResult Search(string searchString)
        //{
        //    var Deceaseds = from m in db.Deceaseds
        //                     select m;
        //    return View(Deceaseds);
        //}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Deceased deceased)
        {
            //if (ModelState.IsValid)
            //{
            Deceased dec = db.Deceaseds.ToList().Find(x => x.deceasedNo == deceased.deceasedNo);
            if (dec != null)
            {
                Session["Response"] = "**This person has already been declared as deceased**";
                Session["DeceasedNo"] = deceased.deceasedNo;
            }
            else
            {
                deceased.firstName = Session["First Name"].ToString();
                deceased.lastName = Session["Last Name"].ToString();
                deceased.idNo = Session["ID Number"].ToString();
                deceased.age = Convert.ToInt32(Session["Age"].ToString());
                //deceased.gender = Session["Gender"].ToString();
                deceased.policyNo = Session["PolicyNo"].ToString();
                List<FileDetail> fileDetails = new List<FileDetail>();
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        FileDetail fileDetail = new FileDetail()
                        {
                            FileName = fileName,
                            Extension = Path.GetExtension(fileName),
                            Id = Guid.NewGuid()
                        };
                        fileDetails.Add(fileDetail);

                        var path = Path.Combine(Server.MapPath("~/App_Data/Upload/"), fileDetail.Id + fileDetail.Extension);
                        file.SaveAs(path);
                    }
                }

                deceased.FileDetails = fileDetails;
                db.Deceaseds.Add(deceased);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            ////}
            return View(deceased);

        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deceased deceased = db.Deceaseds.Include(s => s.FileDetails).SingleOrDefault(x => x.deceasedNo == id);
            if (deceased == null)
            {
                return HttpNotFound();
            }
            return View(deceased);
        }
        public FileResult Download(String p, String d)
        {
            return File(Path.Combine(Server.MapPath("~/App_Data/Upload/"), p), System.Net.Mime.MediaTypeNames.Application.Octet, d);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Deceased deceased)
        {
            if (ModelState.IsValid)
            {
                //New Files
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        FileDetail fileDetail = new FileDetail()
                        {
                            FileName = fileName,
                            Extension = Path.GetExtension(fileName),
                            Id = Guid.NewGuid(),
                            deceasedN = deceased.deceasedNo
                        };
                        var path = Path.Combine(Server.MapPath("~/App_Data/Upload/"), fileDetail.Id + fileDetail.Extension);
                        file.SaveAs(path);

                        db.Entry(fileDetail).State = EntityState.Added;
                    }
                }

                db.Entry(deceased).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(deceased);
        }



        [HttpPost]
        public JsonResult DeleteFile(string id)
        {
            if (String.IsNullOrEmpty(id))
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { Result = "Error" });
            }
            try
            {
                Guid guid = new Guid(id);
                FileDetail fileDetail = db.FileDetails.Find(guid);
                if (fileDetail == null)
                {
                    Response.StatusCode = (int)HttpStatusCode.NotFound;
                    return Json(new { Result = "Error" });
                }

                //Remove from database
                db.FileDetails.Remove(fileDetail);
                db.SaveChanges();

                //Delete file from the file system
                var path = Path.Combine(Server.MapPath("~/App_Data/Upload/"), fileDetail.Id + fileDetail.Extension);
                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deceased deceased = db.Deceaseds.Find(id);
            if (deceased == null)
            {
                return HttpNotFound();
            }
            return View(deceased);
        }

        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Deceased deceased = db.Deceaseds.Find(id);
            db.Deceaseds.Remove(deceased);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Deceased deceased = db.Deceaseds.Find(id);
            if (deceased == null)
            {
                return HttpNotFound();
            }
            return View(deceased);
        }
    }
}

GFS/Views/Deceaseds/Create.cshtml
@model GFS.Models.Policies.Deceased

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Declare As Deceased</h2>


@using (Html.BeginForm("Create", "Deceaseds", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.policyNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Session["PolicyNo"].ToString()
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Session["First Name"].ToString()
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Session["Last Name"].ToString()
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Session["ID Number"].ToString()

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Session["Age"].ToString()

            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Session["Gender"].ToString()

                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.causeOfDeath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.TextAreaFor(model => model.causeOfDeath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.causeOfDeath, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.placeofdeath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.TextAreaFor(model => model.placeofdeath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.placeofdeath, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DateOfDeath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.DateOfDeath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfDeath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="editor-label">
            <label>Upload Deceased Verification Documents:</label>
        </div>
        <div class="editor-field">
            <input type="file" name="file" multiple="multiple" />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
    if (Session["Response"] != null)
    {
        <script>alert(@Session["Response"].ToString())</script>
    }
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

GFS/Views/Deceaseds/Delete.cshtml
@model GFS.Models.Policies.Deceased

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Deceased</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.idNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.placeofdeath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.placeofdeath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.causeOfDeath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.causeOfDeath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfDeath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfDeath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.policyNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.policyNo)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GFS/Views/Deceaseds/Details.cshtml
@model GFS.Models.Policies.Deceased

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Deceased</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.policyNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.policyNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.idNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.age)
        </dd>

        <dt>
        <dt>
            @Html.DisplayNameFor(model => model.causeOfDeath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.causeOfDeath)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.placeofdeath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.placeofdeath)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateOfDeath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfDeath)
        </dd>





    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.deceasedNo }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GFS/Views/Deceaseds/Edit.cshtml
@model GFS.Models.Policies.Deceased

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Deceased</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.deceasedNo)
        <div class="form-group">
            @Html.LabelFor(model => model.policyNo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.policyNo)
                @Html.ValidationMessageFor(model => model.policyNo)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.firstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstName)
                @Html.ValidationMessageFor(model => model.firstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastName)
                @Html.ValidationMessageFor(model => model.lastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idNo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.idNo)
                @Html.ValidationMessageFor(model => model.idNo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.age, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.age)
                @Html.ValidationMessageFor(model => model.age)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.causeOfDeath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.causeOfDeath)
                @Html.ValidationMessageFor(model => model.causeOfDeath)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.placeofdeath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.placeofdeath)
                @Html.ValidationMessageFor(model => model.placeofdeath)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfDeath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfDeath)
                @Html.ValidationMessageFor(model => model.DateOfDeath)
            </div>
        </div>
        <div class="editor-label">
            <label>Uploaded Files:</label>
        </div>
        <div class="editor-field">
            <ul class="attachment">
                @foreach (var item in Model.FileDetails)
                {
                    <li>
                        <a class="title" href="/Deceaseds/Download/?p=@(item.Id + item.Extension)&d=@item.FileName">@item.FileName</a> ||
                        <a href="javascript:void(0);" data-id="@item.Id" class="deleteItem">Delete File</a>
                    </li>
                }
            </ul>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save Changes" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script>
        $('.deleteItem').click(function (e) {
            e.preventDefault();
            var $ctrl = $(this);
            if (confirm('Do you really want to delete this file?')) {
                $.ajax({
                    url: '@Url.Action("DeleteFile")',
                    type: 'POST',
                    data: { id: $(this).data('id') }
                }).done(function (data) {
                    if (data.Result == "OK") {
                        $ctrl.closest('li').remove();
                    }
                    else if (data.Result.Message) {
                        alert(data.Result.Message);
                    }
                }).fail(function () {
                    alert("There is something wrong. Please try again.");
                })

            }
        });
    </script>
}

GFS/Views/Deceaseds/Index.cshtml
@model IEnumerable<GFS.Models.Policies.Deceased>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Deceased</h2>

<table class="table table-bordered table-responsive">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.policyNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.firstName)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.lastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.idNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.causeOfDeath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.placeofdeath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfDeath)
        </th>

        <th>Total Files</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.policyNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.firstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.idNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.causeOfDeath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.placeofdeath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfDeath)
            </td>

            <td>
                @if (item.FileDetails.Count() == 0)
                {
                    <span>No File</span>
                }
                else
                {
                    <span>@item.FileDetails.Count() File(s)</span>
                }
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.deceasedNo }) |
                @Html.ActionLink("Details", "Details", new { id = item.deceasedNo }) |
                <a href="javascript:void(0);" data-id="@item.deceasedNo" class="deleteItem">Delete</a>
            </td>
        </tr>
    }

</table>

@section Scripts {

    <script>
            $('.deleteItem').click(function (e) {
                e.preventDefault();
                var $ctrl = $(this);
                if (confirm('Do you really want to delete this item?')) {
                    $.ajax({
                        url: '@Url.Action("Delete")',
                        type: 'POST',
                        data: { id: $(this).data('id') }
                    }).done(function (data) {
                        if (data.Result == "OK") {
                            $ctrl.closest('tr').remove();
                        }
                        else if (data.Result.Message) {
                            alert(data.Result.Message);
                        }
                    }).fail(function () {
                        alert("There is something wrong. Please try again.");
                    })

                }
            });
    </script>
}